### ISSUE TITLE
提供的fk_ir中没看到有fk_sg.pt文件

### ISSUE THREAD

**Issue by gysabc** [Junction4Nako/mvp_pytorch#4]
想执行readme.md里面的Training with evaluation on the validation split部分的代码，但发现--sent_sg指定的文件并不在提供的下载链接的fk_ir里面

**Comment by Junction4Nako** [comment]
phrase concept相关的文件可以在https://drive.google.com/file/d/1fl8vXvxw9ZXmLaQ6a_4KrM-Zi1w_PgwN/view?usp=sharing这里下载
